### PR TITLE
Avoid code duplication for the ecommerce frontend service 

### LINKED ISSUE #156: Problems building store-frontend-broken-no-instrumentation
On attempt to build the store-frontend-broken-no-instrumentation it looks like there's an error with a pulled depedency

```
docker build .
[+] Building 13.6s (11/13)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 694B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/ruby:2.5.1              0.7s
 => [1/9] FROM docker.io/library/ruby:2.5.1@sha256:ac6661b87cf49af14b1930  0.0s
 => [internal] load build context                                          0.9s
 => => transferring context: 28.66MB                                       0.9s
 => CACHED [2/9] RUN apt-get update -qq &&   apt-get install -y build-ess  0.0s
 => CACHED [3/9] COPY . /spree                                             0.0s
 => CACHED [4/9] WORKDIR /spree                                            0.0s
 => CACHED [5/9] RUN bundle install                                        0.0s
 => CACHED [6/9] RUN bundle update sassc && bundle exec rake store-fronte  0.0s
 => ERROR [7/9] RUN cd store-frontend && bundle update sassc              11.8s
------
 > [7/9] RUN cd store-frontend && bundle update sassc:
#9 0.530 fatal: Not a git repository (or any of the parent directories): .git
#9 0.537 fatal: Not a git repository (or any of the parent directories): .git
#9 0.543 fatal: Not a git repository (or any of the parent directories): .git
#9 0.546 fatal: Not a git repository (or any of the parent directories): .git
#9 0.550 fatal: Not a git repository (or any of the parent directories): .git
#9 0.554 fatal: Not a git repository (or any of the parent directories): .git
#9 0.559 fatal: Not a git repository (or any of the parent directories): .git
#9 0.749 The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
#9 0.751 Fetching https://github.com/spree/spree_gateway.git
#9 1.666 Fetching https://github.com/spree/spree_auth_devise.git
#9 3.011 Fetching gem metadata from https://rubygems.org/...........
#9 6.438 Fetching gem metadata from https://rubygems.org/.............
#9 8.264 Fetching gem metadata from https://rubygems.org/.............
#9 10.85 Resolving dependencies....
#9 11.35 Your bundle is locked to mimemagic (0.3.3), but that version could not be found
#9 11.35 in any of the sources listed in your Gemfile. If you haven't changed sources,
#9 11.35 that means the author of mimemagic (0.3.3) has removed it. You'll need to update
#9 11.35 your bundle to a version other than mimemagic (0.3.3) that hasn't been removed
#9 11.35 in order to install.
------
executor failed running [/bin/sh -c cd store-frontend && bundle update sassc]: exit code: 7
make: *** [build] Error 1
```

### PR DESCRIPTION
**Pull request by arapulido**
Right now we have three versions for the spree application:

* store-frontend-broken-no-instrumentation
* store-frontend-broken-instrumented
* store-frontend-instrumented-fixed

There is a lot of duplication of code on those three versions (most of it is equal), and it makes maintenance a bit cumbersome. For example, store-frontend-broken-no-instrumentation has been broken (not the app, but also the build ;-)) for a while, see #156 

This PR modifies how we are building those images. We have a single folder for store-frontend with the following structure:

```
.
└── store-frontend
    ├── src
    │   ├── store-frontend-initial-state
    │   ├── instrumented-fixed.patch
    │   └── broken-instrumented.patch
    └── storefront-versions
        ├── store-frontend-broken-no-instrumentation
        │   └── Dockerfile
        ├── store-frontend-broken-instrumented
        │   └── Dockerfile
        └── store-frontend-instrumented-fixed
            └── Dockerfile
```

We have a unique application folder (corresponding with broken-non-instrumented) and we build the rest based on that one by patching the changes. We apply the patches as part of the Dockerbuild

To build the docker images, you need to be in the ./store-frontend folder as Docker context and:

`docker build -f storefront-versions/store-frotend-broken-no-instrumentation/Dockerfile .` 

If this gets accepted, I need to create some developer documentation before merging, but I wanted to get some opinions on this first.

Fixes #156

### CODE REVIEW

**Comment by shermdog** [comment]
I have yet to attempt building/testing, but looking through it, this is undisputed PR of the year 🥇

**Comment by arapulido** [comment]
I have added documentation for developers. I think this is ready to be tested, reviewed and ~eventually~ merged

**Comment by stanleegoodspeed** [comment]
Hey @arapulido, I tested this out today and it works well! The only issue I see is that the various `docker-compose` files need to have their `volume` paths updated to reflect the new dir structure

e.g. in `deploy/docker-compose/docker-compose-broken-instrumented.yml` 

```
volumes:
      - "../../store-frontend-broken-instrumented:/app"
```

should become

```
    volumes:
      - "../../store-frontend/src/store-frontend-broken-instrumented:/app"
```

I can take care of this if you want

**Comment by arapulido** [comment]
@stanleegoodspeed mmm, this is an interesting point that you bring. I can work on that, but we should also ask the training team if there are any current courses that clone this repo and expects a specific tree structure. I will ask around.

**Comment by ryanmaclean** [comment]
Re: volume mounts, I know this is something @obensource and I have been using for front end workshop-y stuff! <3

**Comment by arapulido** [comment]
@stanleegoodspeed I added a commit to modify the paths and added some documentation

**Comment by stanleegoodspeed** [comment]
@arapulido Everything looks good on my end. I went through the local dev process with Nick and David as well, and we had no issues. 

Are there any other teams we need to notify prior to merging this in? Would this affect any on-going labs currently using docker compose as the deployment method?

**Review by stanleegoodspeed — APPROVED** [review]

**Comment by arapulido** [comment]
Merged

**Pull request merged**
